// GENERATED FILE — do not edit. Run `pnpm gen:dart` after changing
// packages/shared/src/themes.ts.

import 'package:flutter/painting.dart';

/// Colour tokens of one theme (same names as the web CSS variables).
class OvlPalette {
  const OvlPalette({
    required this.id,
    required this.name,
    required this.description,
    required this.dark,
    required this.bg,
    required this.surface,
    required this.surface2,
    required this.surface3,
    required this.border,
    required this.borderStrong,
    required this.text,
    required this.text2,
    required this.text3,
    required this.accent,
    required this.accent2,
    required this.accentSoft,
    required this.accentText,
    required this.gradFrom,
    required this.gradTo,
    required this.success,
    required this.successSoft,
    required this.warning,
    required this.warningSoft,
    required this.danger,
    required this.dangerSoft,
    required this.owner,
    required this.ownerSoft,
    required this.admin,
    required this.adminSoft,
    required this.council,
    required this.councilSoft,
    required this.moderator,
    required this.moderatorSoft,
    required this.manager,
    required this.managerSoft,
    required this.support,
    required this.supportSoft,
    required this.sidebarBg,
    required this.sidebarText,
    required this.sidebarMuted,
    required this.sidebarActiveBg,
    required this.sidebarActiveText,
    required this.sidebarBorder,
  });

  final String id;
  final String name;
  final String description;
  final bool dark;
  final Color bg;
  final Color surface;
  final Color surface2;
  final Color surface3;
  final Color border;
  final Color borderStrong;
  final Color text;
  final Color text2;
  final Color text3;
  final Color accent;
  final Color accent2;
  final Color accentSoft;
  final Color accentText;
  final Color gradFrom;
  final Color gradTo;
  final Color success;
  final Color successSoft;
  final Color warning;
  final Color warningSoft;
  final Color danger;
  final Color dangerSoft;
  final Color owner;
  final Color ownerSoft;
  final Color admin;
  final Color adminSoft;
  final Color council;
  final Color councilSoft;
  final Color moderator;
  final Color moderatorSoft;
  final Color manager;
  final Color managerSoft;
  final Color support;
  final Color supportSoft;
  final Color sidebarBg;
  final Color sidebarText;
  final Color sidebarMuted;
  final Color sidebarActiveBg;
  final Color sidebarActiveText;
  final Color sidebarBorder;
}

/// Every theme, in the order the pickers show them.
const List<OvlPalette> ovlPalettes = [
  OvlPalette(
    id: 'daylight',
    name: 'Daylight',
    description: 'Crisp and bright, for long working days.',
    dark: false,
    bg: Color(0xFFF4F6FA),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFF1F4F9),
    surface3: Color(0xFFE6EAF2),
    border: Color(0xFFE3E8F0),
    borderStrong: Color(0xFFCBD3E0),
    text: Color(0xFF0F172A),
    text2: Color(0xFF475569),
    text3: Color(0xFF7B8698),
    accent: Color(0xFF2563EB),
    accent2: Color(0xFF1D4ED8),
    accentSoft: Color(0xFFE7EEFE),
    accentText: Color(0xFFFFFFFF),
    gradFrom: Color(0xFF2563EB),
    gradTo: Color(0xFF7C3AED),
    success: Color(0xFF16A34A),
    successSoft: Color(0xFFE3F6EA),
    warning: Color(0xFFC2700C),
    warningSoft: Color(0xFFFEF3E2),
    danger: Color(0xFFDC2626),
    dangerSoft: Color(0xFFFDE8E8),
    owner: Color(0xFFB7791F),
    ownerSoft: Color(0xFFFBF1DC),
    admin: Color(0xFFDC2626),
    adminSoft: Color(0xFFFDE8E8),
    council: Color(0xFF7C3AED),
    councilSoft: Color(0xFFF0E9FE),
    moderator: Color(0xFF2563EB),
    moderatorSoft: Color(0xFFE6EEFE),
    manager: Color(0xFF059669),
    managerSoft: Color(0xFFDEF6EE),
    support: Color(0xFF0891B2),
    supportSoft: Color(0xFFDDF4F9),
    sidebarBg: Color(0xFFFFFFFF),
    sidebarText: Color(0xFF334155),
    sidebarMuted: Color(0xFF8A94A6),
    sidebarActiveBg: Color(0xFFE7EEFE),
    sidebarActiveText: Color(0xFF1D4ED8),
    sidebarBorder: Color(0xFFE3E8F0),
  ),
  OvlPalette(
    id: 'midnight',
    name: 'Midnight',
    description: 'Deep navy with an electric blue accent.',
    dark: true,
    bg: Color(0xFF0A0F1E),
    surface: Color(0xFF10172C),
    surface2: Color(0xFF161F3A),
    surface3: Color(0xFF1E2949),
    border: Color(0xFF1F2A4B),
    borderStrong: Color(0xFF324069),
    text: Color(0xFFE7EBF6),
    text2: Color(0xFFA9B3CF),
    text3: Color(0xFF6E7998),
    accent: Color(0xFF5B8CFF),
    accent2: Color(0xFF82A7FF),
    accentSoft: Color(0xFF1A2A55),
    accentText: Color(0xFFFFFFFF),
    gradFrom: Color(0xFF3B82F6),
    gradTo: Color(0xFF8B5CF6),
    success: Color(0xFF34D399),
    successSoft: Color(0xFF0F3029),
    warning: Color(0xFFFBBF24),
    warningSoft: Color(0xFF3A2C0B),
    danger: Color(0xFFF87171),
    dangerSoft: Color(0xFF3B1418),
    owner: Color(0xFFF5C451),
    ownerSoft: Color(0xFF3A2E10),
    admin: Color(0xFFF87171),
    adminSoft: Color(0xFF3B1418),
    council: Color(0xFFB794F6),
    councilSoft: Color(0xFF2B1F4D),
    moderator: Color(0xFF6B9BFF),
    moderatorSoft: Color(0xFF1A2A55),
    manager: Color(0xFF34D399),
    managerSoft: Color(0xFF0F3029),
    support: Color(0xFF22D3EE),
    supportSoft: Color(0xFF0B3440),
    sidebarBg: Color(0xFF0D1326),
    sidebarText: Color(0xFFB8C1DB),
    sidebarMuted: Color(0xFF5F6A8A),
    sidebarActiveBg: Color(0xFF1A2A55),
    sidebarActiveText: Color(0xFFFFFFFF),
    sidebarBorder: Color(0xFF1A2442),
  ),
  OvlPalette(
    id: 'graphite',
    name: 'Graphite',
    description: 'Neutral charcoal with a warm amber highlight.',
    dark: true,
    bg: Color(0xFF111111),
    surface: Color(0xFF191919),
    surface2: Color(0xFF212121),
    surface3: Color(0xFF2B2B2B),
    border: Color(0xFF2C2C2C),
    borderStrong: Color(0xFF404040),
    text: Color(0xFFEDEDED),
    text2: Color(0xFFB4B4B4),
    text3: Color(0xFF7A7A7A),
    accent: Color(0xFFF59E0B),
    accent2: Color(0xFFFBBF24),
    accentSoft: Color(0xFF3A2A0A),
    accentText: Color(0xFF141414),
    gradFrom: Color(0xFFF59E0B),
    gradTo: Color(0xFFEF4444),
    success: Color(0xFF4ADE80),
    successSoft: Color(0xFF12301D),
    warning: Color(0xFFFACC15),
    warningSoft: Color(0xFF3A320A),
    danger: Color(0xFFF87171),
    dangerSoft: Color(0xFF3B1616),
    owner: Color(0xFFF5C451),
    ownerSoft: Color(0xFF3A2E10),
    admin: Color(0xFFF87171),
    adminSoft: Color(0xFF3B1418),
    council: Color(0xFFB794F6),
    councilSoft: Color(0xFF2B1F4D),
    moderator: Color(0xFF60A5FA),
    moderatorSoft: Color(0xFF16283F),
    manager: Color(0xFF34D399),
    managerSoft: Color(0xFF0F3029),
    support: Color(0xFF22D3EE),
    supportSoft: Color(0xFF0B3440),
    sidebarBg: Color(0xFF151515),
    sidebarText: Color(0xFFC8C8C8),
    sidebarMuted: Color(0xFF6E6E6E),
    sidebarActiveBg: Color(0xFF2A2210),
    sidebarActiveText: Color(0xFFFBBF24),
    sidebarBorder: Color(0xFF242424),
  ),
  OvlPalette(
    id: 'emerald',
    name: 'Emerald',
    description: 'Private-banking green on soft mint.',
    dark: false,
    bg: Color(0xFFF2F7F4),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFEDF4F0),
    surface3: Color(0xFFDFEAE4),
    border: Color(0xFFDAE6DF),
    borderStrong: Color(0xFFBACDC3),
    text: Color(0xFF0B1F16),
    text2: Color(0xFF3E5A4D),
    text3: Color(0xFF728A7E),
    accent: Color(0xFF047857),
    accent2: Color(0xFF065F46),
    accentSoft: Color(0xFFDCF3E9),
    accentText: Color(0xFFFFFFFF),
    gradFrom: Color(0xFF047857),
    gradTo: Color(0xFF0EA5E9),
    success: Color(0xFF15803D),
    successSoft: Color(0xFFE1F4E6),
    warning: Color(0xFFB45309),
    warningSoft: Color(0xFFFDF0DC),
    danger: Color(0xFFB91C1C),
    dangerSoft: Color(0xFFFBE5E5),
    owner: Color(0xFFB7791F),
    ownerSoft: Color(0xFFFBF1DC),
    admin: Color(0xFFDC2626),
    adminSoft: Color(0xFFFDE8E8),
    council: Color(0xFF7C3AED),
    councilSoft: Color(0xFFF0E9FE),
    moderator: Color(0xFF2563EB),
    moderatorSoft: Color(0xFFE6EEFE),
    manager: Color(0xFF047857),
    managerSoft: Color(0xFFDEF6EE),
    support: Color(0xFF0891B2),
    supportSoft: Color(0xFFDDF4F9),
    sidebarBg: Color(0xFF0B3527),
    sidebarText: Color(0xFFCFE8DC),
    sidebarMuted: Color(0xFF78A392),
    sidebarActiveBg: Color(0xFF13513C),
    sidebarActiveText: Color(0xFFFFFFFF),
    sidebarBorder: Color(0xFF0F4332),
  ),
  OvlPalette(
    id: 'obsidian',
    name: 'Obsidian',
    description: 'True black for OLED screens, violet accent.',
    dark: true,
    bg: Color(0xFF000000),
    surface: Color(0xFF0B0B0D),
    surface2: Color(0xFF131316),
    surface3: Color(0xFF1C1C21),
    border: Color(0xFF1F1F25),
    borderStrong: Color(0xFF303038),
    text: Color(0xFFF4F4F5),
    text2: Color(0xFFA1A1AA),
    text3: Color(0xFF6B6B76),
    accent: Color(0xFF8B5CF6),
    accent2: Color(0xFFA78BFA),
    accentSoft: Color(0xFF221A3D),
    accentText: Color(0xFFFFFFFF),
    gradFrom: Color(0xFF8B5CF6),
    gradTo: Color(0xFFEC4899),
    success: Color(0xFF22C55E),
    successSoft: Color(0xFF0E2A18),
    warning: Color(0xFFEAB308),
    warningSoft: Color(0xFF2E2606),
    danger: Color(0xFFEF4444),
    dangerSoft: Color(0xFF2E0E0E),
    owner: Color(0xFFF5C451),
    ownerSoft: Color(0xFF3A2E10),
    admin: Color(0xFFF87171),
    adminSoft: Color(0xFF3B1418),
    council: Color(0xFFB794F6),
    councilSoft: Color(0xFF2B1F4D),
    moderator: Color(0xFF6B9BFF),
    moderatorSoft: Color(0xFF1A2A55),
    manager: Color(0xFF34D399),
    managerSoft: Color(0xFF0F3029),
    support: Color(0xFF22D3EE),
    supportSoft: Color(0xFF0B3440),
    sidebarBg: Color(0xFF050506),
    sidebarText: Color(0xFFC4C4CC),
    sidebarMuted: Color(0xFF5E5E68),
    sidebarActiveBg: Color(0xFF1D1633),
    sidebarActiveText: Color(0xFFFFFFFF),
    sidebarBorder: Color(0xFF141418),
  ),
  OvlPalette(
    id: 'ivory',
    name: 'Ivory',
    description: 'Warm paper tones with a terracotta accent.',
    dark: false,
    bg: Color(0xFFF6F2EA),
    surface: Color(0xFFFFFDF8),
    surface2: Color(0xFFF1EBE1),
    surface3: Color(0xFFE7DECF),
    border: Color(0xFFE4DACA),
    borderStrong: Color(0xFFCDBFA9),
    text: Color(0xFF231C14),
    text2: Color(0xFF5C5043),
    text3: Color(0xFF8C7F6F),
    accent: Color(0xFFB4532A),
    accent2: Color(0xFF9A4422),
    accentSoft: Color(0xFFF5E3D8),
    accentText: Color(0xFFFFFFFF),
    gradFrom: Color(0xFFB4532A),
    gradTo: Color(0xFFD4A24C),
    success: Color(0xFF3F7D3A),
    successSoft: Color(0xFFE5F0E1),
    warning: Color(0xFFA8620F),
    warningSoft: Color(0xFFFAEAD1),
    danger: Color(0xFFB42318),
    dangerSoft: Color(0xFFF9E1DE),
    owner: Color(0xFF9A6A12),
    ownerSoft: Color(0xFFFBF1DC),
    admin: Color(0xFFDC2626),
    adminSoft: Color(0xFFFDE8E8),
    council: Color(0xFF7C3AED),
    councilSoft: Color(0xFFF0E9FE),
    moderator: Color(0xFF2563EB),
    moderatorSoft: Color(0xFFE6EEFE),
    manager: Color(0xFF059669),
    managerSoft: Color(0xFFDEF6EE),
    support: Color(0xFF0891B2),
    supportSoft: Color(0xFFDDF4F9),
    sidebarBg: Color(0xFFEEE6D8),
    sidebarText: Color(0xFF4A3F33),
    sidebarMuted: Color(0xFF948672),
    sidebarActiveBg: Color(0xFFFFFDF8),
    sidebarActiveText: Color(0xFF9A4422),
    sidebarBorder: Color(0xFFE0D5C2),
  ),
  OvlPalette(
    id: 'aurora',
    name: 'Aurora',
    description: 'Dark teal with a northern-lights gradient.',
    dark: true,
    bg: Color(0xFF061519),
    surface: Color(0xFF0B2026),
    surface2: Color(0xFF102A31),
    surface3: Color(0xFF16353D),
    border: Color(0xFF18343B),
    borderStrong: Color(0xFF244E57),
    text: Color(0xFFE2F4F3),
    text2: Color(0xFF9BC3C3),
    text3: Color(0xFF5E898B),
    accent: Color(0xFF2DD4BF),
    accent2: Color(0xFF5EEAD4),
    accentSoft: Color(0xFF0F3A36),
    accentText: Color(0xFF04201C),
    gradFrom: Color(0xFF2DD4BF),
    gradTo: Color(0xFFA855F7),
    success: Color(0xFF4ADE80),
    successSoft: Color(0xFF0E3020),
    warning: Color(0xFFFBBF24),
    warningSoft: Color(0xFF352A0B),
    danger: Color(0xFFFB7185),
    dangerSoft: Color(0xFF3A1520),
    owner: Color(0xFFF5C451),
    ownerSoft: Color(0xFF3A2E10),
    admin: Color(0xFFF87171),
    adminSoft: Color(0xFF3B1418),
    council: Color(0xFFB794F6),
    councilSoft: Color(0xFF2B1F4D),
    moderator: Color(0xFF6B9BFF),
    moderatorSoft: Color(0xFF1A2A55),
    manager: Color(0xFF34D399),
    managerSoft: Color(0xFF0F3029),
    support: Color(0xFF2DD4BF),
    supportSoft: Color(0xFF0F3A36),
    sidebarBg: Color(0xFF081B20),
    sidebarText: Color(0xFFB5D6D6),
    sidebarMuted: Color(0xFF557D80),
    sidebarActiveBg: Color(0xFF0F3A36),
    sidebarActiveText: Color(0xFF5EEAD4),
    sidebarBorder: Color(0xFF10292F),
  ),
  OvlPalette(
    id: 'contrast',
    name: 'High contrast',
    description: 'Maximum legibility and strong outlines.',
    dark: false,
    bg: Color(0xFFFFFFFF),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFF2F2F2),
    surface3: Color(0xFFE0E0E0),
    border: Color(0xFF1A1A1A),
    borderStrong: Color(0xFF000000),
    text: Color(0xFF000000),
    text2: Color(0xFF1F1F1F),
    text3: Color(0xFF3D3D3D),
    accent: Color(0xFF0040C1),
    accent2: Color(0xFF002F8F),
    accentSoft: Color(0xFFDCE6FF),
    accentText: Color(0xFFFFFFFF),
    gradFrom: Color(0xFF0040C1),
    gradTo: Color(0xFF0040C1),
    success: Color(0xFF0B6B2E),
    successSoft: Color(0xFFDDF2E4),
    warning: Color(0xFF8A4B00),
    warningSoft: Color(0xFFFFEBCC),
    danger: Color(0xFFB00020),
    dangerSoft: Color(0xFFFFE0E5),
    owner: Color(0xFFB7791F),
    ownerSoft: Color(0xFFFBF1DC),
    admin: Color(0xFFDC2626),
    adminSoft: Color(0xFFFDE8E8),
    council: Color(0xFF7C3AED),
    councilSoft: Color(0xFFF0E9FE),
    moderator: Color(0xFF2563EB),
    moderatorSoft: Color(0xFFE6EEFE),
    manager: Color(0xFF059669),
    managerSoft: Color(0xFFDEF6EE),
    support: Color(0xFF0891B2),
    supportSoft: Color(0xFFDDF4F9),
    sidebarBg: Color(0xFFFFFFFF),
    sidebarText: Color(0xFF000000),
    sidebarMuted: Color(0xFF3D3D3D),
    sidebarActiveBg: Color(0xFF000000),
    sidebarActiveText: Color(0xFFFFFFFF),
    sidebarBorder: Color(0xFF000000),
  ),
];
