/**
 * Rebuild the Russian catalog from scripts/i18n/ru/*.json — packages/shared/src/locales/ru.ts
 * (web, admin panel, server) and clients/app/lib/i18n/ru.g.dart (apps) — and report texts that
 * have no Russian yet (`pnpm i18n` extracts them first).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const dir = path.join(__dirname, 'ru');
const catalog: Record<string, string> = {};
const conflicts: string[] = [];
for (const file of fs
  .readdirSync(dir)
  .filter((f) => /^part\d+\.json$/.test(f))
  .sort()) {
  const part = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8')) as Record<string, string>;
  for (const [k, v] of Object.entries(part))
    if (k in catalog && catalog[k] !== v) conflicts.push(`${file}: ${k}`);
  Object.assign(catalog, part);
}
if (conflicts.length) {
  console.error(`Translated twice, differently:\n${conflicts.join('\n')}`);
  process.exitCode = 1;
}
const plurals = JSON.parse(fs.readFileSync(path.join(dir, 'plurals.json'), 'utf8')) as Record<
  string,
  string[]
>;

const keys = JSON.parse(fs.readFileSync(path.join(__dirname, 'keys.json'), 'utf8')) as string[];
// Codes, tickers, MIME types and examples read the same in every language.
const verbatim = (k: string) =>
  !/[A-Za-z]/.test(k) ||
  !/\p{Ll}{2}/u.test(k.replace(/\{\d+\}/g, '')) ||
  /^(Application|Image|Text)\//.test(k) ||
  /^https?:/.test(k);
const missing = keys.filter((k) =>
  k.startsWith('plural:')
    ? !plurals[k.slice(7)] && !keys.includes(`plural:${k.slice(7)}`)
    : !(k in catalog) && !verbatim(k),
);
const pluralMissing = keys
  .filter((k) => k.startsWith('plural:'))
  .map((k) => k.slice(7))
  .filter((k) => !plurals[k] && !/s$/.test(k));

// A translation has to use the same {0}, {1}… as its English text.
const holes = (text: string) =>
  [...text.matchAll(/\{\d+\}/g)]
    .map((m) => m[0])
    .sort()
    .join();
const mismatched = Object.keys(catalog).filter((k) => holes(k) !== holes(catalog[k]!));
if (mismatched.length) {
  console.error(`Placeholders differ from the English text:\n${mismatched.join('\n')}`);
  process.exitCode = 1;
}

const entries = Object.keys(catalog)
  .sort((a, b) => a.localeCompare(b))
  .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(catalog[k])},`);
const pluralEntries = Object.keys(plurals)
  .sort()
  .map((k) => `  ${JSON.stringify(k)}: [${plurals[k]!.map((f) => JSON.stringify(f)).join(', ')}],`);
fs.writeFileSync(
  path.join(__dirname, '..', '..', 'packages', 'shared', 'src', 'locales', 'ru.ts'),
  `// Generated by scripts/i18n/build-catalog.ts from scripts/i18n/ru/*.json — edit those.
/** Russian translations, keyed by the English text. */
export const ru: Record<string, string> = {
${entries.join('\n')}
};

/** Plural forms [one, few, many] for nouns counted with plural(). */
export const ruPlurals: Record<string, readonly [string, string, string]> = {
${pluralEntries.join('\n')}
};
`,
);
// The same catalog for the native apps (clients/app), as JSON in raw strings: dart format leaves
// string contents alone, so the file is already formatted as generated.
const json = (value: unknown) => {
  const text = JSON.stringify(value, null, 1);
  if (text.includes("'''")) throw new Error("A translation contains '''");
  return text;
};
const sortedCatalog = Object.fromEntries(
  Object.keys(catalog)
    .sort((a, b) => a.localeCompare(b))
    .map((k) => [k, catalog[k]]),
);
const sortedPlurals = Object.fromEntries(
  Object.keys(plurals)
    .sort()
    .map((k) => [k, plurals[k]]),
);
fs.writeFileSync(
  path.join(__dirname, '..', '..', 'clients', 'app', 'lib', 'i18n', 'ru.g.dart'),
  `// Generated by scripts/i18n/build-catalog.ts from scripts/i18n/ru/*.json — edit those.
import 'dart:convert';

/// Russian translations, keyed by the English text.
final Map<String, String> ru = Map<String, String>.from(jsonDecode(_ru) as Map);

/// Plural forms [one, few, many] for nouns counted with plural().
final Map<String, List<String>> ruPlurals = (jsonDecode(_plurals) as Map).map(
  (key, value) => MapEntry(key as String, List<String>.from(value as List)),
);

const _ru = r'''
${json(sortedCatalog)}
''';

const _plurals = r'''
${json(sortedPlurals)}
''';
`,
);
console.log(`${entries.length} translations, ${pluralEntries.length} plural nouns.`);
const unused = Object.keys(catalog).filter((k) => !keys.includes(k));
if (unused.length) console.log(`Not used any more (${unused.length}): ${unused.join(' | ')}`);
if (missing.length) console.log(`Without Russian (${missing.length}):\n${missing.join('\n')}`);
// CI: every text needs a translation.
if (process.argv.includes('--strict') && (missing.length || pluralMissing.length)) process.exitCode = 1;
if (pluralMissing.length) console.log(`Plural nouns without forms: ${pluralMissing.join(', ')}`);
